### ISSUE TITLE
Build failure with Epoxy.Avalonia11 on .NET 9.0 SDK (MSB6003 error)

### ISSUE THREAD

**Issue by InuInu2022** [kekyo/Epoxy#47]
#### **Description**

Using the .NET 9.0 SDK with Epoxy results in a build failure. An MSB6003 error is displayed.  
This issue was confirmed with `Epoxy.Avalonia11`.

---

#### **Steps to Reproduce**
1. Create a new C# project using the Avalonia xplat template with the .NET 9.0 SDK.  
2. Install the `Epoxy.Avalonia11` NuGet package.  
3. Replace `CommunityToolkit.MVVM` with `Epoxy` and update the `ViewModel` accordingly.  
4. Observe a build error.

---

#### **Expected Behavior**
The build succeeds even with the .NET 9.0 SDK.

---

#### **Actual Behavior**
The build fails when using the .NET 9.0 SDK.  
The build succeeds when using the .NET 8.0 SDK.

---

#### **Screenshots or Logs**
Here is the log output when the error occurs:  

```
【Path】\.nuget\packages\epoxy.build\1.15.0\build\Epoxy.Build.targets(111,5): error MSB6003:
      指定されたタスク実行可能ファイル "cmd.exe" を実行できませんでした。
      System.IO.DirectoryNotFoundException:  作業ディレクトリ "【Path】\.nuget\
      packages\epoxy.build\1.15.0\tools\net9.0" が存在しません。
         at Microsoft.Build.Tasks.Exec.GetWorkingDirectory()
         at Microsoft.Build.Utilities.ToolTask.GetProcessStartInfo(String pathToTool      , String commandLineCommands, String responseFileSwitch)
         at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String       responseFileCommands, String commandLineCommands)
         at Microsoft.Build.Tasks.Exec.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
         at Microsoft.Build.Utilities.ToolTask.Execute()
```

---

#### **Environment**
- OS: Windows 10 Home (22H2)
- Application Version: v1.15.0
- .NET Runtime: 9.0.100

---

#### **Additional Information**

I haven't investigated the cause in detail, but it seems that a similar build error occurs with `Epoxy.Wpf` as well.

**Comment by kekyo** [comment]
Fixed 1.16.0, will be deployed in few minutes.
Could you please test new version?

**Comment by InuInu2022** [comment]
Thank you very much. I checked with the latest version and the build went through successfully.
